### ISSUE TITLE
Adding free goods in receipt 

### ISSUE THREAD

**Issue by Zartemius** [Zartemius/ProjectCashRegister#1]
Creation of a fragment that being launched after clicking the button "Свободный товар в чек". After clicking the button user sees a fragment that gives an opportunity to add a product in receipt stating name of product and price. The data is entered through customized keyboard on a screen.

**Comment by s-kapatsevich** [comment]
@Zartemius как успехи? Когда ждать демонстрацию.

**Comment by Zartemius** [comment]
Почти закончил активити, через которое добавляются свободные товары в чек. Осталось с одной клавишей разобраться и покрасить часть клавиш через которые происходит ввод знаков. Таким образом в активити две клавиатуры: одна для возможности ввести название товара (системная клавиатура), а вторая (кастомная) для ввода цены. При нажатии кнопки "добавить в чек" вылезает сообщение с инфой о добавленном товаре.  Начал тестить на Nexus, подогнал размеры макетов под планшетный экран. Прилагаю скрины. В процессе понял, что реализация большинства окон через фрагменты не совсем удачное решение, поэтому пришлось все переделывать, чтобы реализовать всё через шаблон MVVM, он позволяет связать независимые друг от друга активити через базу данных.  Я создал вторую таблицу в базе данных которая и представляет собой чек, создал у чека модель, которая получает данные из базы и из неё данные уже попадают в UI. При добавлении товара чек происходит то же самое только в обратном порядке. При нажатии кнопки "очистить" в окне "чек" база данных очищается от данных. Подготовился к реализации поиска из базы товаров, которая так же позволит добавлять товары в чек, пока захардкодил (скрин прилагаю). Осталось не так много. Закончу окно  добавления свободных товаров, закрою этот issue. Потом реализую поиск в отдельной issue. Затем создам активити для возможности расчёта. Окончательно подгонять под дизайн макетов in Zeplin буду в самом конце. В феврале хочу уже всё продемонстрировать. 
![screenshot_20180125-234550](https://user-images.githubusercontent.com/23198641/35413558-e2233f58-0230-11e8-8ffa-e7cace5670d6.png)
![screenshot_20180125-234534](https://user-images.githubusercontent.com/23198641/35413559-e246464c-0230-11e8-99d2-43db414461e6.png)
![screenshot_20180125-234508](https://user-images.githubusercontent.com/23198641/35413562-e2665efa-0230-11e8-82a3-1c8b659001a7.png)
![screenshot_20180125-234438](https://user-images.githubusercontent.com/23198641/35413563-e28ca18c-0230-11e8-8a84-ea603bcd31c5.png)
![screenshot_20180125-234323](https://user-images.githubusercontent.com/23198641/35413564-e2af3bf2-0230-11e8-86ca-e028e67fea40.png)
